apiVersion: v1
kind: Service
metadata:
  name: spring-boot-k8-service
  labels:
    name: spring-boot-k8-service
spec:
  type: LoadBalancer  # use ClusterIP as type here
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: spring-boot-k8